services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: yoezer_hotel_web
    privileged: true
    ports: 
     - "80:3000"
    volumes: 
     - .:/rails
    depends_on:
      - db
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://thukten:thukten@db:5432/yoezer_hotel_db
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY_BASE: abdd276a31fbde7262a343a31bf4e00b536e4d72579fb09907302f1754f9e0873ce1456c1456c1420ff7bbe11152d06340627264bb29cb12e9f11b855a71d443e28d0
      user: "1000:1000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: thukten
      POSTGRES_PASSWORD: thukten
      POSTGRES_DB: yoezer_hotel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data

  sidekiq:
    image: yoezer_hotel_web
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis
      - web 
    env_file: 
      - .env
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://thukten:thukten@db:5432/yoezer_hotel_db
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY_BASE: abdd276a31fbde7262a343a31bf4e00b536e4d72579fb09907302f1754f9e0873ce1456c1456c1420ff7bbe11152d06340627264bb29cb12e9f11b855a71d443e28d0    
      user: "1000:1000"
    command: bundle exec sidekiq

volumes:
  postgres_data:
  redis_data:
